# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      mode: :lint,
      path: "MyIOSCIDemo",
      strict: true
    )
  end


  desc "Run unit tests"
  lane :test do
    run_tests(
      scheme: "MyIOSCIDemo",
      devices: ["iPhone 17"],
      clean: false,
      code_coverage: false,
      result_bundle: false
    )
  end


  desc "Run lint and tests"
  lane :ci do
    puts "🔍 Running SwiftLint..."
    lint

    puts "🧪 Running unit tests..."
    test

    puts "✅ CI checks passed!"
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    # Fetch certificates & profiles
  match(
    type: "appstore",
    api_key: api_key,
    readonly: true          # safer for CI
  )

  build_app(
    scheme: "MyIOSCIDemo",
    export_method: "app-store"
  )

  upload_to_testflight(
    api_key: api_key,
    skip_waiting_for_build_processing: true   # optional but useful
  )
  end

end
